import { useClerk, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import { FaEdit, FaCalendar } from "react-icons/fa";
import { MdOutlineGridView } from "react-icons/md";
import relativeTime from "dayjs/plugin/relativeTime";
import Head from "next/head";
import dayjs from "dayjs";
import Image from "next/image";

dayjs.extend(relativeTime);

const ProfilePage: NextPage = () => {
  const { user } = useUser();
  const isUserSignedIn = useUser().isSignedIn;
  const clerk = useClerk();

  if (!isUserSignedIn) return <div onLoad={void clerk.openSignIn({})}></div>;
  if (!user) return null;
  if (!user.username) return null;
  if (!user.createdAt) return null;

  const month = dayjs(user.createdAt).fromNow();

  if (!month) return null;

  return (
    <>
      <Head>
        <title>Pedestal</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="absolute z-10 w-[100vw] py-4 px-6 md:left-[50%] md:ml-[-400px] md:w-[800px] lg:left-[50%] lg:ml-[-550px] lg:w-[1100px]">
        <div className="mx-auto mt-20">
          <div>
            <Image
              className="mx-auto rounded-full border-white-100/75"
              src={user.profileImageUrl}
              alt={"user.png"}
              width={120}
              height={120}
            />
          </div>
          <div className="text-center text-white-100">
            <h1 className="mt-6 text-xl font-bold">{user.username}</h1>
          </div>
          <div className="text-center text-white-100/75">
            <div className="inline-flex">
              <span className="mt-[3px] mr-1">
                <FaCalendar />
              </span>
              <span>Joined {month}</span>
              <span>&nbsp;&bull;&nbsp;</span>
              <span className="mt-1 mr-1">
                <MdOutlineGridView />
              </span>
              <span>X showcases</span>
            </div>
          </div>
          <div className="mt-4 h-[1px] w-full bg-white-200/25" />
        </div>
      </main>
    </>
  );
};

export default ProfilePage;
